# To not confict with other tools that use go-template (like helm, ArgoCD AppSet, etc.)
# Let's use << and >> instead of {{ and }}
leftDelim: '<<'
rightDelim: '>>'

context:
  .:
    url: variables.yaml