# https://taskfile.dev
version: '3'

vars:
  kindConfig: kind.yaml
  ciliumVersion: 1.13.1
  ingressNginxVersion: 4.6.1
  argoVersion: 5.34.5

tasks:
  run:
    desc: Create a kind cluster from the config file
    silent: true
    preconditions:
      - sh: which kind
        msg: "kind is not installed. Please install it from https://kind.sigs.k8s.io/docs/user/quick-start/#installation"
      - sh: which helm
        msg: "helm is not installed. Please install it from https://helm.sh/docs/intro/install/"
      - sh: which kubectl
        msg: "kubectl is not installed. Please install it from https://kubernetes.io/docs/tasks/tools/install-kubectl/"
      - sh: which gomplate
        msg: "gomplate is not installed. Please install it from https://docs.gomplate.ca/installing/"
    cmds:
      - kind create cluster --config={{ .kindConfig }}
      - task: bootstrap

  stop:
    silent: true
    desc: Stop the kind cluster
    cmds:
      - kind delete cluster

  bootstrap:
    # internal: true
    # silent: true
    desc: Bootstraps the cluster with Cilium and Ingress Nginx
    cmds:
      - gomplate --input-dir templates/bootstrap --output-dir out/
      # - helm repo add cilium https://helm.cilium.io/
      # - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      # - helm repo add argo https://argoproj.github.io/argo-helm
      # - helm repo update
      # - >
      #   helm install cilium cilium/cilium
      #   --version {{ .ciliumVersion }}
      #   -f ./out/values/cilium.yaml
      #   --namespace=kube-system
      # - >
      #   helm install ingress-nginx ingress-nginx/ingress-nginx
      #   --version {{ .ingressNginxVersion }}
      #   -f ./out/values/ingress-nginx.yaml
      #   --namespace ingress-nginx --create-namespace
      - >
        helm install argo argo/argo-cd
        --version {{ .argoVersion }}
        -f ./out/values/argocd.yaml
        --namespace argocd
        --create-namespace
      - rm -rf ./out