# https://taskfile.dev
version: '3'

vars:
  kindConfig: kind.yaml

tasks:
  run:
    desc: Create a kind cluster from the config file
    preconditions:
      - sh: which kind
        msg: "kind is not installed. Please install it from https://kind.sigs.k8s.io/docs/user/quick-start/#installation"
      - sh: which helm
        msg: "helm is not installed. Please install it from https://helm.sh/docs/intro/install/"
      - sh: which kubectl
        msg: "kubectl is not installed. Please install it from https://kubernetes.io/docs/tasks/tools/install-kubectl/"
      - sh: which gomplate
        msg: "gomplate is not installed. Please install it from https://docs.gomplate.ca/installing/"
      - sh: which yq
        msg: "yq is not installed. Please install it from https://mikefarah.gitbook.io/yq/#install"
    cmds:
      - kind create cluster --config={{ .kindConfig }}
      - task: bootstrap

  stop:
    desc: Stop the kind cluster
    cmds:
      - kind delete cluster

  cleanup:
    desc: Cleanup templated directories
    cmds:
      - rm -rf {argocd,apps} || true

  template:
    desc: Generate the ArgoCD apps manifests
    cmds:
      - task: cleanup
      - gomplate --input-dir templates/argocd --output-dir argocd/
      - gomplate --input-dir templates/apps --output-dir apps/

  bootstrap:
    # internal: true
    desc: Bootstraps the cluster with Cilium and Ingress Nginx
    cmds:
      - task: template
      - helm repo add cilium https://helm.cilium.io/
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
      - >
        helm install cilium cilium/cilium
        --version $(yq -r < variables.yaml .versions.cilium)
        -f ./apps/core/values/cilium.yaml
        --namespace=kube-system
      - >
        helm install argocd argo/argo-cd
        --version $(yq -r < variables.yaml .versions.argocd)
        -f ./apps/core/values/argocd.yaml
        --namespace argocd
        --create-namespace
      - kubectl apply -k ./apps/core/argocd-core