---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: << .repository.url >>
      revision: << .repository.branch >>
      directories:
      - path: argocd/*
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        parent-appset: argocd-apps
    spec:
      ## argocd/>infra</argo-cd
      project: '{{ path[1] }}'
      source:
        repoURL: << .repository.url >>
        targetRevision: << .repository.branch >>
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - Validate=true
        - CreateNamespace=true
        - PruneLast=true