
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: addons
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 46.4.1
      helm:
        valueFiles:
          - $values/apps/addons/values/kube-prometheus-stack.yaml
    - repoURL: https://github.com/devOwlish/home-lab.git
      targetRevision: init
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
