---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-core
  namespace: argocd
spec:
  project: core
  source:
    path: apps/core/argocd-core
    repoURL: https://github.com/devOwlish/home-lab.git
    targetRevision: init
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PruneLast=true
