---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: core
  # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.6.1
      helm:
        valueFiles:
          - $values/apps/core/values/ingress-nginx.yaml
    - repoURL: https://github.com/devOwlish/home-lab.git
      targetRevision: init
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PruneLast=true
