---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: core
  # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: << .versions.argocd >>
      helm:
        valueFiles:
          - $values/apps/core/values/argocd.yaml
    - repoURL: << .repository.url >>
      targetRevision: << .repository.branch >>
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PruneLast=true
