---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infra
  # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.6.1
      helm:
        valueFiles:
          - $values/manifests/ingress-nginx/values.yaml
    - repoURL: << .repository.url >>
      targetRevision: << .repository.branch >>
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PruneLast=true
